### ISSUE TITLE
Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by nim-f** [numical/style-ext-html-webpack-plugin#44]
Plugin doesn't work with ejected create-react-app, webpack version is  4.29.6

**Comment by numical** [comment]
Hi,
Can I get a bit more detail?
package.json
webpack.config
etc.

Also does it work before ejection?

**Comment by Kupstas** [comment]
Any news?

**Comment by SpyTec** [comment]
Getting the same error, also with ejected CRA. Very similar to the config nim-f posted

**Comment by nim-f** [comment]
I had same kind of problem with another plugin, then replaced   compilation.hooks.htmlWebpackPluginAlterAssetTags.tap with HtmlWebpackPlugin.getHooks(e).alterAssetTags.tap and it worked.

Seems api of HtmlWebpackPlugin changed and plugins need to be updated as well

**Comment by SpyTec** [comment]
Workaround might be to use an older version of HtmlWebpackPlugin then. Will try tomorrow and report back (if I remember)

**Comment by SpyTec** [comment]
Could not downgrade HtmlWebpackPlugin due to dependencies. Though looking at the source and changing stuff I encoutnered this
```
Plugin could not be registered at 'htmlWebpackPluginBeforeHtmlProcessing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
```

Which happened when I changed:

```diff
-if (compilation.hooks) {
+if (compilation.hooks && compilation.hooks[event]) {
  debug('MikeE', event);
  debug('MikeE', compilation.hooks);
  compilation.hooks[event].tapAsync('StyleExtHtmlWebpackPlugin', wrappedFn);
} else {
  compilation.plugin(event, wrappedFn);
}
```

Though I've yet to figure out anything further

**Comment by SpyTec** [comment]
Tried changing it around
```js

// HtmlWebpackPlugin 4.x and later
const htmlWebpackHookEvents = {
  htmlWebpackPluginBeforeHtmlProcessing: 'beforeAssetTagGeneration',
  htmlWebpackPluginAlterAssetTags: 'alterAssetTags',
  htmlWebpackPluginAfterHtmlProcessing: 'afterTemplateExecution'
}

//...

if (compilation.hooks) {
  debug('MikeE', event);
  debug('MikeE', compilation.hooks);

  if (compilation.hooks[event]) {
    compilation.hooks[event].tapAsync('StyleExtHtmlWebpackPlugin', wrappedFn);
  }
  else {
    // deals with HtmlWebpackPlugin 4
    var HtmlWebpackPlugin = require('html-webpack-plugin');
    var hooks = HtmlWebpackPlugin.getHooks(compilation);
    hooks[htmlWebpackHookEvents[event]].tapAsync('StyleExtHtmlWebpackPlugin', wrappedFn);
  }
}
```

Yet now I'm encountering 

```
./node_modules/@patternfly/react-styles/css/components/OptionsMenu/options-menu.css
TypeError: this[MODULE_TYPE] is not a function
```

And although that TypeError is not part of this library, I'm not sure if it is causing the issue

**Comment by SpyTec** [comment]
The code above does work, tried it without MiniCssExtractPlugin and it encountered no issues.

Though I'm getting the TypeError issue together with MiniCssExtractPlugin (formerly ExtractTextWebpackPlugin). I'm unsure as to why

**Comment by numical** [comment]
Hi - working on this.
I now have successfully breaking tests (!) for HtmlWebpackPlugin v4  on branch [feature/html-webpack-plugin-4-support](https://github.com/numical/style-ext-html-webpack-plugin/tree/feature/html-webpack-plugin-4-support) and getting these fixed based on @SpyTec's suggested [PR](https://github.com/numical/style-ext-html-webpack-plugin/pull/45).

**Comment by numical** [comment]
That was easier than expected.
v4.1.0 now support HtmlWebpackPlugin v4.x. and will no longer encounter this error.
Thanks @SpyTec!

**Comment by JZO001** [comment]
Looks like the issue is still exist :( I just copy paste the example code into my webpack config file, latest version installed from this plugin and when I run, I get tapAsync issue again. Anybody can help me please?

**Comment by sayjeyhi** [comment]
I am facing this issue too, any updates?
```bash
      beforeGenerationHook.tapPromise('AddAssetHtmlPlugin', htmlPluginData =>
                           ^

TypeError: Cannot read property 'tapPromise' of undefined
    at compiler.hooks.compilation.tap.compilation (/Users/macbook/Desktop/snapp/new-website/node_modules/add-asset-html-webpack-plugin/lib/index.js:119:28)
    at SyncHook.eval [as call] (eval at create (/Users/macbook/Desktop/snapp/new-website/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
    at SyncHook.lazyCompileHook (/Users/macbook/Desktop/snapp/new-website/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/macbook/Desktop/snapp/new-website/node_modules/webpack/lib/Compiler.js:631:26)
    at hooks.beforeCompile.callAsync.err (/Users/macbook/Desktop/snapp/new-website/node_modules/webpack/lib/Compiler.js:667:29)
```

**Comment by lwj06** [comment]
I had same kind of problem, cannot read property 'tapasync' of undefined at compiler.hooks.compilation.tap.compilation, Anybody can help me please?

![image](https://user-images.githubusercontent.com/5893392/80447681-b119cf80-894c-11ea-893e-3f011855b8ab.png)

node 8.9.0 
webpack ^4.15.1
electron 2.0.4

**Comment by lwj06** [comment]
I had same kind of problem, cannot read property 'tapasync' of undefined at compiler.hooks.compilation.tap.compilation, Anybody can help me please?

![image](https://user-images.githubusercontent.com/5893392/80451671-ffcc6700-8956-11ea-9c7c-0651b77a59a5.png)
node 8.9.0
webpack ^4.15.1
html-webpack-plugin 4.2.0
electron 2.0.4

**Comment by MikeMitterer** [comment]
The only solution I found was to downgrade to 3.2.0

The same here:
```bash
/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/html-beautify-webpack-plugin/index.js:46
            compilation.hooks.htmlWebpackPluginAfterHtmlProcessing.tapAsync('HtmlBeautifyPlugin', (htmlPluginData, callback) => {
                                                                   ^

TypeError: Cannot read property 'tapAsync' of undefined
    at /Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/html-beautify-webpack-plugin/index.js:46:68
    at SyncHook.eval [as call] (eval at create (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/webpack/lib/Compiler.js:631:26)
    at /Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/webpack/lib/Compiler.js:662:28)
    at /Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/webpack/lib/Watching.js:77:18
    at _next0 (eval at create (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at eval (eval at create (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at LiveReloadPlugin.serverStarted (/Volumes/DevLocal/DevTypeScript/Production/mobiad/auth/node_modules/webpack-livereload-plugin/index.js:89:9)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:314:20)
    at emitListeningNT (net.js:1350:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
```
